name: Build and Release

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]**"

jobs:

  agent_test:
    uses: ./.github/workflows/agent_test.yml

  configdocsgenerator_test:
    uses: ./.github/workflows/configdocsgenerator_test.yml

  configurationserver_test:
    uses: ./.github/workflows/configurationserver_test.yml

  configuration_ui_test:
    uses: ./.github/workflows/configuration_ui_test.yml

  build_and_release:
    name: 'Build and Release'
    runs-on: ubuntu-latest
    environment: release
    #needs: [configdocsgenerator_test, configurationserver_test, configuration_ui_test]
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build artifacts
        run: |
          ./gradlew assemble bootJarWithFrontend :inspectit-ocelot-core:cyclonedxBom :inspectit-ocelot-configurationserver:cyclonedxBom -PbuildVersion=${{ github.ref_name }}
          mkdir artifacts
          cp ./inspectit-ocelot-agent/build/inspectit-ocelot-agent-${{ github.ref_name }}.jar ./artifacts
          cp ./components/inspectit-ocelot-configurationserver/build/libs/inspectit-ocelot-configurationserver-${{ github.ref_name }}.jar ./artifacts
          mkdir boms
          cp ./inspectit-ocelot-core/build/reports/bom.json ./boms/inspectit-ocelot-agent-bom.json
          cp ./inspectit-ocelot-core/build/reports/bom.xml ./boms/inspectit-ocelot-agent-bom.xml
          cp ./components/inspectit-ocelot-configurationserver/build/reports/bom.json ./boms/inspectit-ocelot-configurationserver-bom.json
          cp ./components/inspectit-ocelot-configurationserver/build/reports/bom.xml ./boms/inspectit-ocelot-configurationserver-bom.xml
          zip -r ./artifacts/software-bill-of-materials.zip ./boms
      # Uploading jars to create docker images
      - name: Upload inspectit-ocelot-agent jar
        uses: actions/upload-artifact@v3
        with:
          name: inspectit-ocelot-agent-jar
          path: artifacts/inspectit-ocelot-agent-${{ github.ref_name }}.jar
      - name: Upload inspectit-ocelot-configurationserver jar
        uses: actions/upload-artifact@v3
        with:
          name: inspectit-ocelot-configurationserver-jar
          path: artifacts/inspectit-ocelot-configurationserver-${{ github.ref_name }}.jar 
      - name: Calculate checksums of release artifacts
        working-directory: ./artifacts
        run: for f in *; do sha256sum "$f" >> inspectit-ocelot-sha256-checksums.txt; done
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ github.event.inputs.boomerang-version }}
          files: artifacts/*
          generate_release_notes: true
          token: ${{ github.token }}
          name: Version ${{ github.ref_name }}
          body: "You can also find the corresponding documentation online under the following link: [inspectIT Ocelot Documentation](http://docs.inspectit.rocks)"

  publish_docker_image:
    name: "Publish docker image"
    runs-on: ubuntu-latest
    needs: [build_and_release]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Downloading jars to create docker image
      - name: Download inspectit-ocelot-agent jar
        uses: actions/download-artifact@v3
        with: 
          name: inspectit-ocelot-agent-jar # name as reference
          path: inspectit-ocelot-agent/docker/
      - name: Download inspectit-ocelot-configurationserver jar
        uses: actions/download-artifact@v3
        with: 
          name: inspectit-ocelot-configurationserver-jar # name as reference
          path: components/inspectit-ocelot-configurationserver/docker/
      - name: Check if inspectit-ocelot-agent jar exists and rename it
        run: |
          cd inspectit-ocelot-agent/docker
          mv inspectit-ocelot-agent-${{ github.ref_name }}.jar inspectit-ocelot-agent.jar
          ls
      - name: Check if inspectit-ocelot-configurations jar exists and rename it
        run: |
          cd components/inspectit-ocelot-configurationserver/docker
          mv inspectit-ocelot-configurationserver-${{ github.ref_name }}.jar inspectit-ocelot-configurationserver.jar
          ls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push inspectit-ocelot-agent image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: danipaniii/inspectit-ocelot-agent${{ github.ref_name }}, danipaniii/inspectit-ocelot-agent:latest
          file: ./inspectit-ocelot-agent/docker/Dockerfile
      - name: Build and push inspectit-ocelot-configurationserver image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: danipaniii/inspectit-ocelot-configurationserver${{ github.ref_name }}, danipaniii/inspectit-ocelot-configurationserver:latest
          file: ./components/inspectit-ocelot-configurationserver/docker/Dockerfile

  build_documentation:
    name: "Build and Publish Release Documentation"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inspectit-ocelot-documentation/website
    needs: build_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'inspectit-ocelot-documentation/website/yarn.lock'
      - name: Replace Variables in Docs
        working-directory: ./inspectit-ocelot-documentation/docs
        run: |
          find . -type f -print0 | xargs -0 sed -i 's/{inspectit-ocelot-version}/'"${{ github.ref_name }}"'/g'
          OPEN_CENSUS_VERSION=$(cat ../../gradle.properties | grep -oP '(?<=openCensusVersion=).*')
          find . -type f -print0 | xargs -0 sed -i 's/{opencensus-version}/'"${OPEN_CENSUS_VERSION}"'/g'
      - name: Create new Documentation Version
        run: |
          npm install
          npm run version ${{ github.ref_name }}
          git add versions.json versioned_docs versioned_sidebars
          git config --global user.name 'NTTechnicalUser'
          git config --global user.email 'NTTechnicalUser@users.noreply.github.com'
          git commit -m "Publish documentation for release ${{ github.ref_name }}"
          git push -f origin HEAD:master
      - name: Install Build Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./inspectit-ocelot-documentation/website/build/inspectit-ocelot
          user_name: NTTechnicalUser
          user_email: NTTechnicalUser@users.noreply.github.com
          commit_message: Publish documentation for release ${{ github.ref_name }}
